# Generated by Django 3.0.4 on 2020-03-30 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messdiener', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acolyte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('extra', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ageFrom', models.IntegerField()),
                ('ageTo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('extra', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='location',
            old_name='location_name',
            new_name='locationName',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='role_name',
            new_name='roleName',
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('dayOfWeek', models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', ' Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messdiener.Location')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messdiener.Type')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('classifications', models.ManyToManyField(to='messdiener.Classification')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messdiener.Role')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messdiener.Type')),
            ],
        ),
        migrations.CreateModel(
            name='MassAcolyteRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acolyte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messdiener.Acolyte')),
                ('mass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messdiener.Mass')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messdiener.Role')),
            ],
        ),
        migrations.AddField(
            model_name='mass',
            name='acolytes',
            field=models.ManyToManyField(through='messdiener.MassAcolyteRole', to='messdiener.Acolyte'),
        ),
        migrations.AddField(
            model_name='mass',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messdiener.Location'),
        ),
        migrations.AddField(
            model_name='mass',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messdiener.Type'),
        ),
        migrations.AddField(
            model_name='classification',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messdiener.Group'),
        ),
        migrations.AddField(
            model_name='acolyte',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messdiener.Group'),
        ),
    ]
