# Generated by Django 3.0.4 on 2020-03-30 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messdiener', '0002_auto_20200330_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acolyte',
            name='extra',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='acolyte',
            name='group',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='messdiener.Group'),
        ),
        migrations.AlterField(
            model_name='mass',
            name='extra',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='mass',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='messdiener.Location'),
        ),
        migrations.AlterField(
            model_name='mass',
            name='type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='messdiener.Type'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='role',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='messdiener.Role'),
        ),
    ]
