# Generated by Django 3.0.4 on 2020-03-31 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messdiener', '0004_auto_20200330_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='messdiener.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='groupName',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='locationName',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='massacolyterole',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='messdiener.Role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='roleName',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='typeName',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='acolyte',
            unique_together={('firstName', 'lastName', 'extra', 'birthday')},
        ),
        migrations.AlterUniqueTogether(
            name='classification',
            unique_together={('ageFrom', 'ageTo', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='mass',
            unique_together={('time', 'extra', 'location')},
        ),
        migrations.AlterUniqueTogether(
            name='massacolyterole',
            unique_together={('acolyte', 'mass')},
        ),
    ]
