# Generated by Django 3.0.4 on 2020-03-31 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messdiener', '0005_auto_20200331_1325'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requirement',
            unique_together={('quantity', 'role')},
        ),
    ]
