# Generated by Django 3.0.4 on 2020-03-31 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messdiener', '0006_auto_20200401_0030'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requirement',
            unique_together=set(),
        ),
    ]
