# Generated by Django 3.0.4 on 2020-03-31 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messdiener', '0007_auto_20200401_0041'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requirement',
            unique_together={('quantity', 'role', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='rule',
            unique_together={('location', 'time', 'type', 'dayOfWeek')},
        ),
    ]
