# Generated by Django 3.0.5 on 2020-05-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messdiener', '0011_auto_20200521_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mass',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masses', to='messdiener.Plan'),
        ),
    ]
