# Generated by Django 3.0.8 on 2020-07-21 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messdiener', '0012_auto_20200522_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
