# Generated by Django 3.1.6 on 2021-02-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messdiener', '0013_plan_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='acolyte',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
