# Generated by Django 3.1.6 on 2021-02-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messdiener', '0014_acolyte_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='mass',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
    ]
